---
title: Додай зображення і текст поруч
hero_image: images/banner.png
description: Додай зображення і текст поруч.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Додай зображення і текст поруч
