title: Voeg naast elkaar een afbeelding en tekst toe
hero_image: images/banner.png
description: Add side by side image and text.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Voeg naast elkaar een afbeelding en tekst toe
