title: Ajouter une image et un texte côte à côte
hero_image: images/banner.png
description: Ajoute une image et un texte côte à côte
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Ajouter une image et un texte côte à côte
